version: 2.1
workflows:
  test-deploy:
    jobs:
      -test
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      steps:
        - checkout
        - run:
            name: Install Dependencies
            command: mvn install
        - run:
            name: Run Tests
            command: mvn run test

    
